# Generated by Django 2.0.4 on 2018-04-24 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabla', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ideja',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
